services:
  # Backend API Service
  - type: web
    name: awdiii
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: skillshare-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FIREBASE_PROJECT_ID
        value: knoweachother-ba559
      - key: FRONTEND_URL
        value: https://awdiii-1.onrender.com

  # Frontend Static Site with SPA routing
  - type: static
    name: awdiii-1
    plan: free
    buildCommand: rm -rf node_modules && npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /404.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://awdiii.onrender.com/api
